version: "3.8"

services:
  db:
    image: postgres:15
    container_name: featureflag_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: featureflag
    ports:
      - "5433:5432"  # Maps container port 5432 to your localhost:5433 (avoiding conflict)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data between restarts

  redis:
    image: redis:7-alpine
    container_name: featureflag_redis
    ports:
      - "6379:6379"  # Redis default port

volumes:
  postgres_data:
